# Generated by Django 3.1.4 on 2021-01-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_auto_20210129_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
