# Generated by Django 3.1.4 on 2021-01-29 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20210129_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 20, 17, 25, 51244, tzinfo=utc)),
        ),
    ]
